// shared/brand/vue/BrandMotif.vue
<template>
  <div class="brand-motif brand-motif--fixed" aria-hidden="true">
    <template v-if="motif === 'moon'">
      <div class="brand-motif-moon__glow" />
      <div class="brand-motif-moon__disc" />
      <div class="brand-motif-moon__beam" />
    </template>

    <template v-else-if="motif === 'rain'">
      <div class="brand-motif-rain__sheet" />
      <span
        v-for="d in rainDrops"
        :key="d.key"
        class="brand-motif-rain__drop"
        :style="d.style"
      />
    </template>

    <template v-else-if="motif === 'snow'">
      <span
        v-for="f in snowFlakes"
        :key="f.key"
        class="brand-motif-snow__flake"
        :style="f.style"
      />
    </template>

    <template v-else-if="motif === 'thunder'">
      <div class="brand-motif-thunder__pulse" />
      <div class="brand-motif-thunder__vein" />
      <div
        class="brand-motif-thunder__bolt"
        style="--bolt-left: 68%; --bolt-top: 6%; --bolt-delay: 0s; --bolt-cycle: 12s"
      />
      <div
        class="brand-motif-thunder__bolt"
        style="--bolt-left: 22%; --bolt-top: 10%; --bolt-delay: 4.5s; --bolt-cycle: 14s; --bolt-len: 60px"
      />
    </template>

    <template v-else-if="motif === 'leaves'">
      <div class="brand-motif-leaves__haze" />
      <span
        v-for="l in leaves"
        :key="l.key"
        class="brand-motif-leaves__leaf"
        :style="l.style"
      />
    </template>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { buildRainDrops, buildSnowFlakes, buildFallingLeaves } from '../motifBuilders.js'

const props = defineProps({
  motif: {
    type: String,
    required: true,
    validator: (v) => ['rain', 'snow', 'moon', 'thunder', 'leaves'].includes(v),
  },
  /** 雨/雪/叶数量；不传则用默认密度 */
  count: {
    type: Number,
    default: undefined,
  },
})

const rainDrops = computed(() => buildRainDrops(props.count ?? 52))
const snowFlakes = computed(() => buildSnowFlakes(props.count ?? 46))
const leaves = computed(() => buildFallingLeaves(props.count ?? 28))
</script>

// shared/brand/react/BrandMotif.jsx
import { buildRainDrops, buildSnowFlakes, buildFallingLeaves } from '../motifBuilders.js'

const RAIN = buildRainDrops(52)
const SNOW = buildSnowFlakes(56)
const LEAVES = buildFallingLeaves(28)

/**
 * @param {{ motif: 'rain'|'snow'|'moon'|'thunder'|'leaves', fixed?: boolean, className?: string }} props
 */
export default function BrandMotif({ motif, fixed = true, className = '' }) {
  const rootClass = ['brand-motif', fixed ? 'brand-motif--fixed' : '', className].filter(Boolean).join(' ')

  if (motif === 'moon') {
    return (
      <div className={rootClass} aria-hidden="true">
        <div className="brand-motif-moon__glow" />
        <div className="brand-motif-moon__disc" />
        <div className="brand-motif-moon__beam" />
      </div>
    )
  }

  if (motif === 'rain') {
    return (
      <div className={rootClass} aria-hidden="true">
        <div className="brand-motif-rain__sheet" />
        {RAIN.map((d) => (
          <span key={d.key} className="brand-motif-rain__drop" style={d.style} />
        ))}
      </div>
    )
  }

  if (motif === 'snow') {
    return (
      <div className={rootClass} aria-hidden="true">
        {SNOW.map((f) => (
          <span key={f.key} className="brand-motif-snow__flake" style={f.style} />
        ))}
      </div>
    )
  }

  if (motif === 'thunder') {
    return (
      <div className={rootClass} aria-hidden="true">
        <div className="brand-motif-thunder__pulse" />
        <div className="brand-motif-thunder__vein" />
        <div
          className="brand-motif-thunder__bolt"
          style={{ '--bolt-left': '68%', '--bolt-top': '6%', '--bolt-delay': '0s', '--bolt-cycle': '12s' }}
        />
        <div
          className="brand-motif-thunder__bolt"
          style={{ '--bolt-left': '22%', '--bolt-top': '10%', '--bolt-delay': '4.5s', '--bolt-cycle': '14s', '--bolt-len': '60px' }}
        />
      </div>
    )
  }

  if (motif === 'leaves') {
    return (
      <div className={rootClass} aria-hidden="true">
        <div className="brand-motif-leaves__haze" />
        {LEAVES.map((l) => (
          <span key={l.key} className="brand-motif-leaves__leaf" style={l.style} />
        ))}
      </div>
    )
  }

  return null
}
