// Manager_Agent/app/components/AppModal.vue
<template>
  <Teleport to="body">
    <div
      v-if="modelValue"
      class="app-modal-backdrop"
      role="presentation"
      @click.self="onBackdropClick"
    >
      <div class="app-modal-panel" role="dialog" :aria-labelledby="titleId" aria-modal="true">
        <header class="app-modal-header">
          <h3 :id="titleId" class="app-modal-title">{{ title }}</h3>
        </header>
        <div class="app-modal-body">
          <p v-if="message" class="app-modal-message">{{ message }}</p>
          <input
            v-if="mode === 'prompt'"
            v-model="localInput"
            type="text"
            class="app-modal-input"
            :placeholder="inputPlaceholder"
            :maxlength="inputMaxLength"
            @keydown.enter.prevent="onConfirm"
          />
        </div>
        <footer class="app-modal-footer">
          <button
            v-if="mode === 'confirm' || mode === 'prompt'"
            type="button"
            class="spring-btn alt spring-btn-sm app-modal-btn"
            @click="onCancel"
          >
            {{ cancelText }}
          </button>
          <button type="button" class="spring-btn spring-btn-sm app-modal-btn" @click="onConfirm">
            {{ confirmText }}
          </button>
        </footer>
      </div>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from 'vue'

const props = withDefaults(
  defineProps<{
    modelValue: boolean
    mode?: 'alert' | 'confirm' | 'prompt'
    title?: string
    message?: string
    confirmText?: string
    cancelText?: string
    inputValue?: string
    inputPlaceholder?: string
    inputMaxLength?: number
  }>(),
  {
    mode: 'alert',
    title: '提示',
    message: '',
    confirmText: '确定',
    cancelText: '取消',
    inputValue: '',
    inputPlaceholder: '',
    inputMaxLength: 80
  }
)

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
  confirm: [inputValue?: string]
  cancel: []
}>()

const localInput = ref('')

watch(
  () => props.modelValue,
  (open) => {
    if (open && props.mode === 'prompt') localInput.value = String(props.inputValue || '')
  },
  { immediate: true }
)

const titleId = computed(() => `app-modal-title-${Math.random().toString(36).slice(2, 9)}`)

function onConfirm() {
  emit('confirm', props.mode === 'prompt' ? localInput.value : undefined)
  emit('update:modelValue', false)
}

function onCancel() {
  emit('cancel')
  emit('update:modelValue', false)
}

function onBackdropClick() {
  if (props.mode === 'alert') onConfirm()
  else onCancel()
}

function onKeydown(e: KeyboardEvent) {
  if (!props.modelValue) return
  if (e.key === 'Escape') {
    e.preventDefault()
    if (props.mode === 'alert') onConfirm()
    else onCancel()
  }
}

watch(
  () => props.modelValue,
  (open) => {
    if (typeof window === 'undefined') return
    if (open) window.addEventListener('keydown', onKeydown)
    else window.removeEventListener('keydown', onKeydown)
  },
  { immediate: true }
)

onBeforeUnmount(() => {
  if (typeof window !== 'undefined') window.removeEventListener('keydown', onKeydown)
})
</script>

<style scoped>
.app-modal-backdrop {
  position: fixed;
  inset: 0;
  z-index: 9999;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 16px;
  background: rgba(30, 50, 75, 0.48);
  backdrop-filter: blur(8px);
}

.app-modal-panel {
  width: min(440px, 100%);
  border-radius: 14px;
  border: 1px solid rgba(122, 168, 212, 0.55);
  background: linear-gradient(165deg, rgba(255, 255, 255, 0.98) 0%, rgba(238, 245, 252, 0.96) 100%);
  box-shadow: 0 24px 56px rgba(18, 45, 78, 0.18), inset 0 1px 0 rgba(255, 255, 255, 0.9);
  overflow: hidden;
  color: #0e1f30;
}

.app-modal-header {
  padding: 16px 18px 8px;
}

.app-modal-title {
  margin: 0;
  font-size: 16px;
  font-weight: 700;
  color: #0e1f30;
}

.app-modal-body {
  padding: 8px 18px 16px;
}

.app-modal-message {
  margin: 0 0 12px;
  font-size: 14px;
  line-height: 1.55;
  color: #3a536c;
  white-space: pre-wrap;
}

.app-modal-input {
  width: 100%;
  box-sizing: border-box;
  border-radius: 10px;
  border: 1px solid rgba(122, 168, 212, 0.55);
  background: rgba(255, 255, 255, 0.96);
  color: #0e1f30;
  font-size: 14px;
  padding: 10px 12px;
  outline: none;
}

.app-modal-input:focus {
  border-color: rgba(47, 127, 209, 0.65);
  box-shadow: 0 0 0 2px rgba(47, 127, 209, 0.16);
}

.app-modal-footer {
  display: flex;
  justify-content: flex-end;
  gap: 8px;
  padding: 12px 18px 16px;
  border-top: 1px solid rgba(122, 168, 212, 0.35);
}

.app-modal-btn {
  min-width: 72px;
}
</style>

// AI_admin_Agent/frontend/src/AppModal.tsx
import { useEffect, useId, useState } from 'react';

type AppModalMode = 'alert' | 'confirm' | 'prompt';

type AppModalProps = {
  open: boolean;
  mode?: AppModalMode;
  title?: string;
  message?: string;
  confirmText?: string;
  cancelText?: string;
  inputValue?: string;
  inputPlaceholder?: string;
  inputMaxLength?: number;
  onConfirm: (value?: string) => void;
  onCancel: () => void;
};

export function AppModal({
  open,
  mode = 'alert',
  title = '提示',
  message = '',
  confirmText = '确定',
  cancelText = '取消',
  inputValue = '',
  inputPlaceholder = '',
  inputMaxLength = 80,
  onConfirm,
  onCancel,
}: AppModalProps) {
  const titleId = useId();
  const [localInput, setLocalInput] = useState('');

  useEffect(() => {
    if (open && mode === 'prompt') setLocalInput(inputValue || '');
  }, [open, mode, inputValue]);

  useEffect(() => {
    if (!open) return;
    const onKeydown = (e: KeyboardEvent) => {
      if (e.key !== 'Escape') return;
      if (mode === 'alert') onConfirm();
      else onCancel();
    };
    window.addEventListener('keydown', onKeydown);
    return () => window.removeEventListener('keydown', onKeydown);
  }, [open, mode, onConfirm, onCancel]);

  if (!open) return null;

  return (
    <div
      className="admin-modal-backdrop fixed inset-0 z-[60] flex items-center justify-center p-4"
      role="presentation"
      onClick={() => (mode === 'alert' ? onConfirm() : onCancel())}
    >
      <div
        className="admin-modal-dialog relative w-full max-w-[22rem]"
        role="dialog"
        aria-labelledby={titleId}
        aria-modal="true"
        onClick={(e) => e.stopPropagation()}
      >
        <header className="admin-modal-header">
          <h3 id={titleId} className="admin-modal-title">
            {title}
          </h3>
        </header>
        <div className="admin-modal-body">
          {message ? <p className="admin-modal-message">{message}</p> : null}
          {mode === 'prompt' ? (
            <input
              type="text"
              value={localInput}
              maxLength={inputMaxLength}
              placeholder={inputPlaceholder}
              className="admin-modal-input"
              onChange={(e) => setLocalInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter') {
                  e.preventDefault();
                  onConfirm(localInput);
                }
              }}
            />
          ) : null}
        </div>
        <footer className={`admin-modal-footer${mode === 'alert' ? ' admin-modal-footer--alert' : ''}`}>
          {mode === 'confirm' || mode === 'prompt' ? (
            <button type="button" className="admin-modal-btn-secondary" onClick={onCancel}>
              {cancelText}
            </button>
          ) : null}
          <button
            type="button"
            className="admin-modal-btn-primary"
            onClick={() => onConfirm(mode === 'prompt' ? localInput : undefined)}
          >
            {confirmText}
          </button>
        </footer>
      </div>
    </div>
  );
}
